"""Real client exits and SIGKILL, restricted to disposable test clients/guests."""
import json
import os
import select
import signal
import subprocess
import sys
import time
import uuid

import pytest

from sandweave import Sandbox
from sandweave.sandbox.targets import local_connection
from sandweave.templates.resolve import Template

pytestmark = [pytest.mark.integration,
              pytest.mark.skipif(not os.environ.get('SANDWEAVE_INTEGRATION'), reason='explicit worker required')]


@pytest.fixture(scope='module', autouse=True)
def release_idle_test_worker():
    yield
    connection = local_connection()
    try:
        connection.call('_shutdown_if_idle')
    finally:
        connection.close()


@pytest.fixture
def clients(tmp_path):
    processes, names, logs = [], [], []
    # First-use installation can select a new prepared asset root. Prepare
    # before capturing the observer endpoint so child and observer agree.
    connection = local_connection(template=Template('coding').resolve())

    def start(body):
        name = 'ownership-' + uuid.uuid4().hex
        log = (tmp_path / (name + '.log')).open('w+')
        code = 'from sandweave import Sandbox\nimport os, signal, time, sys\nname = ' + repr(name) + '\n' + body
        process = subprocess.Popen([sys.executable, '-c', code], stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE, stderr=log, text=True, start_new_session=True)
        processes.append(process)
        names.append(name)
        logs.append(log)
        return process, name

    yield start, connection
    for process in processes:
        if process.poll() is None:
            process.kill()
        process.wait(timeout=10)
        process.stdout.close()
    try:
        # Match only names generated by this test. Preserve all other records.
        for record in connection.call('list'):
            if record.get('name') in names:
                connection.call('terminate', identity=record['id'])
    finally:
        connection.close()
        for log in logs:
            log.close()


def line(process):
    assert select.select([process.stdout], [], [], 90)[0], 'client did not publish its sandbox'
    value = process.stdout.readline().strip()
    assert value, 'test client exited before publishing; inspect its stderr log'
    return value


def wait_terminated(connection, identity, timeout=15):
    deadline = time.monotonic() + timeout
    while True:
        status = connection.call('describe', identity=identity)
        if status['state'] == 'terminated':
            assert status['runtime_status']['status'] == 'stopped'
            return status
        assert time.monotonic() < deadline, status
        time.sleep(.1)


@pytest.mark.parametrize('ending', ['normal', 'sigint', 'sigterm', 'sigkill', 'os_exit'])
def test_creator_exit_cleans_up_without_python_exit_hooks(clients, ending):
    start, connection = clients
    tail = 'os._exit(0)' if ending == 'os_exit' else 'time.sleep(300)' if ending != 'normal' else ''
    child, _ = start('env = Sandbox(name=name)\nprint(env.id, flush=True)\n' + tail)
    identity = line(child)
    if ending in ('sigint', 'sigterm', 'sigkill'):
        child.send_signal({'sigint': signal.SIGINT, 'sigterm': signal.SIGTERM, 'sigkill': signal.SIGKILL}[ending])
    child.wait(timeout=10)
    assert wait_terminated(connection, identity)['termination_reason'] == 'owner_exited'


def test_close_and_borrowing_do_not_change_process_ownership(clients):
    start, connection = clients
    child, _ = start('env = Sandbox(name=name)\nenv.close()\nprint(env.id, flush=True)\ntime.sleep(300)')
    identity = line(child)
    with Sandbox.connect(identity) as borrowed:
        assert borrowed.run('echo alive').stdout == 'alive\n'
    assert connection.call('describe', identity=identity)['state'] == 'ready'
    child.kill()
    child.wait(timeout=10)
    assert wait_terminated(connection, identity)['termination_reason'] == 'owner_exited'


@pytest.mark.parametrize('detached', [False, True])
def test_killed_creator_of_paused_sandbox_respects_detached(clients, detached):
    start, connection = clients
    child, _ = start(f'env = Sandbox(name=name, detached={detached!r})\nenv.pause()\n'
                     'print(env.id, flush=True)\ntime.sleep(300)')
    identity = line(child)
    child.kill()
    child.wait(timeout=10)
    if detached:
        time.sleep(1)
        with Sandbox.connect(identity) as env:
            assert env.status()['state'] == 'paused'
            env.resume()
            assert env.run('echo survived').stdout == 'survived\n'
            env.terminate()
    else:
        assert wait_terminated(connection, identity)['termination_reason'] == 'owner_exited'


def test_death_during_startup_cleans_even_keep_on_error(clients, tmp_path):
    start, connection = clients
    setup = tmp_path / 'slow.sh'
    setup.write_text('#!/bin/sh\nsleep 60\n')
    child, name = start(f'env = Sandbox(name=name, setup={str(setup)!r}, keep_on_error=True)\n')
    deadline = time.monotonic() + 90
    while True:
        assert child.poll() is None, 'test client failed before startup could be interrupted'
        matches = [item for item in connection.call('list') if item.get('name') == name]
        if matches and matches[0]['state'] == 'preparing':
            identity = matches[0]['id']
            break
        assert time.monotonic() < deadline
        time.sleep(.1)
    child.kill()
    child.wait(timeout=10)
    assert wait_terminated(connection, identity)['termination_reason'] == 'owner_exited'


def test_heartbeat_keeps_remote_owner_alive_then_expires_after_sigkill(clients):
    start, connection = clients
    # Use the real RPC/heartbeat path without local /proc identity. This models
    # a remote client while keeping every process in the disposable allocation.
    child, _ = start('from sandweave.sandbox import ownership\n'
                     'ownership.process_identity = lambda: None\n'
                     'env = Sandbox(name=name)\nprint(env.id, flush=True)\ntime.sleep(300)')
    identity = line(child)
    time.sleep(32)
    assert connection.call('describe', identity=identity)['state'] == 'ready'
    child.kill()
    child.wait(timeout=10)
    assert wait_terminated(connection, identity, timeout=40)['termination_reason'] == 'owner_heartbeat_expired'


@pytest.mark.parametrize('options', ["runtime='apptainer'", "template='gnome'"])
def test_owner_cleanup_with_native_runtime_and_desktop(clients, options):
    start, connection = clients
    if options == "template='gnome'":
        prepared = local_connection(template=Template('gnome').resolve())
        prepared.close()
    child, _ = start(f'env = Sandbox(name=name, {options})\n'
                     'print(env.id, flush=True)\ntime.sleep(300)')
    identity = line(child)
    # Template preparation may extend the imported runtime. Reconnect using
    # the saved selection before observing this new sandbox.
    with Sandbox.connect(identity) as env:
        assert env.run('echo ready').stdout == 'ready\n'
        child.kill()
        child.wait(timeout=10)
        assert wait_terminated(env._connection, identity)['termination_reason'] == 'owner_exited'


def test_pool_reserve_belongs_to_the_calling_process(clients):
    start, connection = clients
    child, _ = start('from sandweave import Pool\nimport json\n'
                     'pool = Pool(size=2, warm=2).start()\n'
                     'print(json.dumps(sorted(env.id for env in pool.all)), flush=True)\ntime.sleep(300)')
    identities = json.loads(line(child))
    assert len(identities) == 2
    try:
        child.kill()
        child.wait(timeout=10)
        for identity in identities:
            assert wait_terminated(connection, identity)['termination_reason'] == 'owner_exited'
    finally:
        # Pool sandboxes have no name; these are exactly the IDs the child gave us.
        for identity in identities:
            connection.call('terminate', identity=identity)
